#ifndef _LANGUAGE_
#define _LANGUAGE_

enum E_KOR_LANG_PART
{
	E_KOR_LANG_NOUN = 0,
	E_KOR_LANG_PRONOUN,
	E_KOR_LANG_NUMERAL,
	E_KOR_LANG_VERB,
	E_KOR_LANG_ADJECTIVE,
	E_KOR_LANG_DETERMINER,
	E_KOR_LANG_ADVERB,
	E_KOR_LANG_JOSA,
	E_KOR_LANG_EXCLAMATION,

	E_KOR_LANG_UNKNOWN
};

#endif